Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CoursePlanner.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using CoursePlanner.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Extensions.Logging;
using System.ComponentModel;
using Highsoft.Web.Mvc.Charts;
using System.Text;
using System.IO;
using System.Xml.Serialization;
using Newtonsoft.Json;

namespace CoursePlanner.Pages
{

    public class IndexModel : PageModel
    {
        private readonly CoursePlanner.Data.CoursePlannerContext _context;


        private readonly ILogger<IndexModel> _logger;

        public JsonResult json;

        List<List<Section>> sectionsDividedToGroups = new List<List<Section>>();

        public CoursePlanner.Scheduler.Scheduler scheduler;
        

        public IndexModel(ILogger<IndexModel> logger, CoursePlanner.Data.CoursePlannerContext context)
        {
            _context = context;
            _logger = logger;
            scheduler = Scheduler.Scheduler.SchedulerInstance(context); ;
        }

        public void OnGet()
        {

        }

        public JsonResult OnGetBubble()
        {
            // 0: start with the lecture sections
            var lecSections = from s in _context.Section
                              where s.Type == "LEC"
                              where s.Capacity > 0
                              select s.ClassId;

            // 1st part 

            var subjects = from c in _context.Class
                           where lecSections.ToList().Contains(c.ClassId)
                           select c.Subject;

            List<string> sortedClassList = new List<string>(subjects);
            sortedClassList.Sort();
            HashSet<string> unique_subjects = new HashSet<string>(sortedClassList);
            /*foreach (string s in unique_subjects)
            {
                Console.WriteLine(s);
            }
            Console.WriteLine(unique_subjects.Count());*/

            // 2nd part

            var classes = from c in _context.Class
                          where lecSections.ToList().Contains(c.ClassId)
                          select c; // subject, code, capacity, prerequisite

            List<Class> classesList = new List<Class>(classes);
            HashSet<Class> unique_classes = new HashSet<Class>(classes);
            Console.WriteLine(unique_classes.Count());

            // 3rd part : the combination
            List<Bubble> bubble_data = new List<Bubble>();

            // 3.1 add the subjects to bubble data
            foreach (string s in unique_subjects)
            {
                Bubble bubble = new Bubble();
                bubble.name = s;

                BubbleClass subjectBubble = new BubbleClass();
                subjectBubble.name = s;
                subjectBubble.value = 100;
                subjectBubble.prereq = null;
                bubble.data = new List<BubbleClass>();

                bubble.data.Add(subjectBubble);

                bubble_data.Add(bubble);
            }

            // 3.2 add the bubble classes to designated subjects
            foreach (Class c in unique_classes)
            {
                BubbleClass bubbleClass = new BubbleClass();
                bubbleClass.name = c.Code.ToString();
                bubbleClass.value = _context.Section.Where(s => s.ClassId.Equals(c.ClassId)).FirstOrDefault<Section>().Capacity;
                bubbleClass.prereq = c.Prerequisite;

                string designated_subject = c.Subject;

                foreach(Bubble b in bubble_data)
                {
                    if (designated_subject.Equals(b.name))
                    {
                        b.data.Add(bubbleClass);
                    }
                }
            }

            // 4th part: out

            /* JSON WRITER WORKS AS WELL
             * 
             * JsonSerializer serializer = new JsonSerializer();
            serializer.NullValueHandling = NullValueHandling.Ignore;

            using (StreamWriter sw = new StreamWriter(@"Pages/bubble_json.json"))
            using (JsonWriter writer = new JsonTextWriter(sw))
            {
                serializer.Serialize(writer, bubble_data);
            }*/

            return new JsonResult(bubble_data);


        }

        public void OnPostRefresh()
        {
            scheduler.ResetChoices();
        }
      
        public void OnPostMakeTimetables()
        {
            if (scheduler.getChoices().Any())
            {
                List<Tuple<string, int>> choices = new List<Tuple<string, int>>();
                choices = scheduler.getChoices();
                foreach (Tuple<string, int> choice in choices)
                {
                    RemoveFaultySectionsAndGroup(choice);
                }
                List<List<Section>> resultingTables = new List<List<Section>>();

                    foreach (Section section in sectionsDividedToGroups[0])
                    {
                            List<Section> currentTable = new List<Section>();
                            currentTable.Add(section);
                            if (sectionsDividedToGroups.Count() > 1)
                            {
                                MakeTimetables(currentTable, 1, resultingTables);
                            }
                            else
                            {
                                resultingTables.Add(currentTable);
                            }
                    }
                TimetableFormatting(resultingTables);
                ViewData["flag"] = "flag";
            }
           
        }

        public void MakeTimetables(List<Section> currentTable, int depth, List<List<Section>> resultingTables)
        {
            List<Section> currentTableForLoop = new List<Section>(currentTable);
                
                foreach (Section section in sectionsDividedToGroups[depth])
                {
                        bool intersects = false;
                        foreach (Section tableSection in currentTableForLoop)
                        {
                            if (scheduler.Collides(section, tableSection))
                            {
                                intersects = true;
                                break;
                            }
                        }
                        if (!intersects)
                        {
                            List<Section> currentTableToPassDown = new List<Section>(currentTable);
                            currentTableToPassDown.Add(section);
                            if (depth < sectionsDividedToGroups.Count() - 1)
                            {
                                MakeTimetables(currentTableToPassDown, depth + 1, resultingTables);
                            }
                            else
                            {
                                resultingTables.Add(currentTableToPassDown);
                            }
                        }
                }
        }

        public void RemoveFaultySectionsAndGroup(Tuple<string, int> choice)
        {
            var chosenClassID = from m in _context.Class
                                where m.Subject == choice.Item1
                                where m.Code == choice.Item2
                                select m.ClassId;

            var chosenClassAllSectionsID = from m in _context.Section
                                           where m.ClassId == chosenClassID.ToList()[0]
                                           select m.SectionId;

            var chosenClassAllSections = from m in _context.Section
                                         where chosenClassAllSectionsID.ToList().Contains(m.SectionId)
                                         select m;
            List<Section> chosenClassAllSectionsList = new List<Section>(chosenClassAllSections);
            foreach (Section section in chosenClassAllSections)
            {
                if (section.Times == "" || section.Times == "0:0-0:0" || section.Times == "Fri ")  //These are bad data
                {
                    chosenClassAllSectionsList.Remove(section);
                    Console.WriteLine("Removed: " + section);
                }
            }
            var groupedSections = chosenClassAllSectionsList.GroupBy(section => section.Type);
            foreach (var group in groupedSections)
            {
                List<Section> sectionByGroups = new List<Section>();
                foreach (Section section in chosenClassAllSectionsList)
                {
                    if(group.Key == section.Type)
                    {
                        sectionByGroups.Add(section);
                    }
                }
                sectionsDividedToGroups.Add(sectionByGroups);
            }
            Console.WriteLine(sectionsDividedToGroups);
        }

        public void TimetableFormatting(List<List<Section>> resultingTable)
        {
            List<string> times = new List<string>() { "8:30-9:45", "10:0-11:15", "11:30-12:45", "13:0-14:15", "14:30-15:45", "16:0-17:15", "17:30-18:45" };
            List<List<List<string>>> formattedTimetable = new List<List<List<string>>>();
            foreach (List<Section> table in resultingTable)
            {
                List<List<string>> formattedTable = new List<List<string>>();
                foreach (string time in times)
                {
                    List<string> timetableRow = new List<string> { time, " ", " ", " ", " ", " " };
                    foreach (Section section in table)
                    {
                        if (section.Times.Contains(time.Substring(0, 5)) || section.Times.Contains(time.Substring(time.Length - 5, 5)))
                        {
                            if (section.Times.Contains("Mon"))
                            {

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CoursePlanner.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@using Highsoft.Web.Mvc.Charts
@using Highsoft.Web.Mvc.Charts.Rendering;
<style>
    input[type=submit] {
        font-family: Georgia;
        font-size: 20px;
        background: #eac9fe;
        border: none;
        border-radius: 5px;
        position: relative;
        left: 50%;
    }

    th {
        text-align: left;
    }

    .timetable {
        border-collapse: collapse;
        font-size: 0.9em;
        margin: 25px 0;
        table-layout: fixed;
        width: 100%;
    }

        .timetable thead tr {
            background-color: #eac9fe;
        }

        .timetable th,
        .timetable td {
            padding: 10px 10px;
        }

        .timetable tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .timetable tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .timetable tbody tr:last-of-type {
                border-bottom: 2px solid #eac9fe;
            }
</style>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div align="right" style="width:950px">
    <form method="post" asp-page-handler="Refresh">
        <input type="submit" value="Refresh">
    </form>
</div>

<figure class="highcharts-figure">
    <div id="container" align="left" style="width:1300px; height: 650px"></div>
</figure>

<div align="center" style="width:800px">
    <form method="post" asp-page-handler="MakeTimetables">
        <input type="submit" value="Show Timetables">
    </form>
</div>


@{
    var flag = ViewData["flag"] as string;
    if (string.Compare(flag, "flag") == 0)
    {
        var count = 0;
        var allTables = ViewData["tables"] as List<List<List<string>>>;
        foreach (List<List<string>> table in allTables)
        {
            count += 1;
            <h2>Timetable @count</h2>
            <table class="timetable">
                <colgroup>
                    <col style="width:150px" />
                    <col style="width:150px" />
                    <col style="width:150px" />
                    <col style="width:150px" />
                    <col style="width:150px" />
                    <col style="width:150px" />
                </colgroup>
                <thead>
                    <tr>
                        <th></th>
                        <th>Monday</th>
                        <th>Tuesday</th>
                        <th>Wednesday</th>
                        <th>Thursday</th>
                        <th>Friday</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (List<string> row in table)
                    {
                        <tr>
                            @foreach (string element in row)
                            {
                                switch (element)
                                {
                                    case "8:30-9:45":
                                        <td>08.30-09.45</td>
                                        break;
                                    case "10:0-11:15":
                                        <td>10.00-11.15</td>
                                        break;
                                    case "11:30-12:45":
                                        <td>11.30-12.45</td>
                                        break;
                                    case "13:0-14:15":
                                        <td>13.00-14.15</td>
                                        break;
                                    case "14:30-15:45":
                                        <td>14.30-15.45</td>
                                        break;
                                    case "16:0-17:15":
                                        <td>16.00-17.15</td>
                                        break;
                                    case "17:30-18:45":
                                        <td>17.30-18.45</td>
                                        break;
                                    default:
                                        <td>@element</td>
                                        break;
                                }
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
    }
}

<script>

    var canClick = true;
    var chart;

    function reddy(subject, code, collision) {
        //console.log(chart.series.length);

        for (var i = 0; i < chart.series.length; i++) {


            if (chart.series[i].name == subject) {
                //console.log(chart.series[i]);
                for (var j = 0; j < chart.series[i].data.length; j++) {

                    //console.log(chart.series[i].data[j].name);
                    if (chart.series[i].data[j].name == code) {
                        //if (chart.series[i].data[j].color == 'pink') {
                        //    var col = chart.series[i].data[j].options.prereq + ", " + collision;
                        //    chart.series[i].data[j].options.prereq = col;
                        //    chart.series[i].data[j].update({ prereq: col });
                        //}
                        if (chart.series[i].data[j].color != 'white' && 'pink') {
                            chart.series[i].data[j].update({ color: 'pink' });
                            var col = chart.series[i].data[j].options.prereq + ", Conflicts with: " + collision;
                            chart.series[i].data[j].options.prereq = col;
                            chart.series[i].data[j].update({ prereq: col });
                        }
                    }
                }


            }
        }
    };

    //
    var options = {
        chart: {
            type: 'packedbubble',
            height: '650',
            width: '1300',
            marginRight: 200
        },
        legend: {
            align: 'left',
            verticalAlign: 'middle',
            width: 200,
            itemWidth: 100
        },
        title: {
            text: 'Fall 2019'
        },
        tooltip: {
            formatter: function () {
                var str = ""
                if (this.series.name != this.point.name) {
                    str = '<b>' + this.series.name + ' ' + this.point.name + ': </b>' + this.point.value + ' students';

                    if (this.point.prereq != null) {
                        str = str.concat(', Prerequisites:' + this.point.prereq);
                    }
                } else {
                    str = '<b>' + this.series.name + ' </b>';
                }
                return str;
            }
        },
        plotOptions: {
            series: {
                visible: false,
            },
            packedbubble: {
                //allowPointSelect: true,
                //selected: false,
                minSize: '10%',
                maxSize: '150%',
                zMin: 0,
                zMax: 1000,
                layoutAlgorithm: {
                    gravitationalConstant: 0.05,
                    friction: -0.9,
                    splitSeries: true,
                    seriesInteraction: false,
                    dragBetweenSeries: false,
                    parentNodeLimit: true
                },
                dataLabels: {
                    enabled: true,
                    formatter: function () {
                        if (this.series.name == this.point.name) {
                            return '<b>' + (this.point.name) + '</b>';
                        }
                        else {
                            return this.point.name;
                        }
                    },
                    style: {
                        color: 'black',
                        textOutline: 'none',
                        fontWeight: 'normal'

                    }
                },
                point: {
                    //selected: false,
                    events: {
                        click: function (e) {
                            if (canClick) {
                                if (this.series.name != this.name) { // must not be subject labelled bubbles
                                    
                                    //if its not selected, select it
                                    if (this.color != 'white') {
                                        canClick = false;
                                        this.update({ color: 'white' });

                                        var sc = "" + this.series.name + this.name;

                                        var sc1 = JSON.stringify(sc);
                                        //console.log(sc);
                                        $.ajax({
                                            type: "POST",
                                            url: "/Index?handler=SelectedCourse",
                                            beforeSend: function (xhr) {
                                                xhr.setRequestHeader("XSRF-TOKEN",
                                                    $('input:hidden[name="__RequestVerificationToken"]').val());
                                            },
                                            data: sc1,
                                            contentType: "application/json; charset=utf-8",
                                            dataType: "json",
                                            success: function (response) {
                                                alert(response);
                                            },
                                            failure: function (response) {
                                                alert(response);
                                            }
                                        });

                                        setTimeout(() => {

                                            $.ajax({
                                                type: "GET",
                                                url: "/Index?handler=Dict",
                                                contentType: "application/json",
                                                dataType: "json",
                                                success: function (response) {
                                                    var dict = response;
                                                    for (var course in dict) {
                                                        var subject = course.substring(0, course.length - 3);
                                                        var code = course.substring(course.length - 3, course.length);
                                                        var collided = dict[course][0];
                                                        
                                                        reddy(subject, code, collided);
                                                    }
                                                },
                                                failure: function (response) {
                                                    alert(response);
                                                }
                                            });

                                            canClick = true;
                                        }, 3000);

                                    } 
                                }
                            }
                        }
                    }
                }
            }
        },
        series: [{}]
    };

    $.ajax({
        type: "GET",
        url: "/Index?handler=Bubble",
        contentType: "application/json",
        dataType: "json",
        success: function (data) {
            console.log(data.length);
            options.series = data;
            chart = new Highcharts.Chart('container', options);
        },
        failure: function (response) {
            alert(response);
        }
    });

</script>